name: simple_mutex
description: Simple but the best Mutex providing a exclusive write lock and shared read-only locks.
version: 2.0.0
homepage: https://github.com/Cat-sushi/simple_mutex

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
